[judged]
pid_file = "/tmp/hustoj.pid"
sleep_time = 1
server_id = 0
log_file = "/tmp/hustoj.log"
data_cache = "/tmp/hoj_data/"

[api]
url = "http://localhost:5000/judge/api/"
judge_id = "1"
code = "d1553bc6-54f0-43d7-9e23-b0eeccd45341"

[mq]
host = "host"
port = 5672
db = "hustoj"
username = "hustoj"
password = "password"
queue = "hustoj"
vhost = "/"
routing_key = "hustoj"

[worker]
path = "/tmp/hustoj"

